// <auto-generated />
using System;
using MQTransaction.Common.DbOperate;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MQTransaction.Common.Migrations
{
    [DbContext(typeof(MQTransDbContext))]
    partial class MQTransDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MQTransaction.Common.Models.Entity.mq_published", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasComment("主键")
                        .HasMaxLength(36);

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("exchange_name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("expires_time")
                        .HasColumnType("datetime(6)")
                        .HasComment("过期时间");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("消息体");

                    b.Property<string>("query_url")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasComment("查询结果地址")
                        .HasMaxLength(255);

                    b.Property<string>("queue_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("remark")
                        .HasColumnType("longtext")
                        .HasComment("备注");

                    b.Property<int>("retries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("重试次数")
                        .HasMaxLength(11)
                        .HasDefaultValue(0);

                    b.Property<string>("route_key")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("service_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasComment("服务名")
                        .HasMaxLength(255);

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasComment("发送状态")
                        .HasMaxLength(11);

                    b.HasKey("id");

                    b.ToTable("mq_published");

                    b.HasComment("消息发送表");
                });

            modelBuilder.Entity("MQTransaction.Common.Models.Entity.mq_received", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasComment("主键")
                        .HasMaxLength(36);

                    b.Property<string>("callback_url")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasComment("回调地址")
                        .HasMaxLength(255);

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime(6)")
                        .HasComment("创建时间");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("消息体");

                    b.Property<string>("queue_name")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4")
                        .HasMaxLength(255);

                    b.Property<string>("source_msg_id")
                        .IsRequired()
                        .HasColumnType("varchar(36) CHARACTER SET utf8mb4")
                        .HasComment("消息发送方id-唯一")
                        .HasMaxLength(36);

                    b.Property<int>("status")
                        .HasColumnType("int")
                        .HasComment("接收状态")
                        .HasMaxLength(11);

                    b.HasKey("id");

                    b.HasIndex("source_msg_id")
                        .IsUnique();

                    b.ToTable("mq_received");

                    b.HasComment("消息接收表");
                });
#pragma warning restore 612, 618
        }
    }
}
